CREATE TABLE IF NOT EXISTS
	products(
		id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
		name VARCHAR(50) NOT NULL,
        description VARCHAR(100) NOT NULL,
        brand VARCHAR(25) NOT NULL,
		image_url VARCHAR(255),
        price INTEGER NOT NULL, 
		category VARCHAR(20) NOT NULL,
		created_at TIMESTAMPTZ DEFAULT NOW(),
		updated_at TIMESTAMPTZ DEFAULT NOW()
	);